POST http://localhost:3003/api/products
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGU1MjUyNTAwZGU2MmVhY2VmOGY0ZCIsImlhdCI6MTY1MjM2MTcyMiwiZXhwIjoxNjUyNDQ4MTIyfQ.IxTcu4EFVZ9-p_IEhfI7wVndDUI6UZc5XHgT9PWELMc

{
    "product_id": "pr001",
    "title": "abc",
    "price": 10,
    "description": "description",
    "content": "content",
    "images": {
        "public_id": "test/yxgfiz4qftg8zj8mfxc4",
        "url": "https://res.cloudinary.com/theklatran/image/upload/v1642976253/test/yxgfiz4qftg8zj8mfxc4.png"
    },
    "category": "programming"
}