DELETE http://localhost:3003/api/products/627d0a15ff3b916f70a138b8
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGU1MjUyNTAwZGU2MmVhY2VmOGY0ZCIsImlhdCI6MTY1MjM2MTcyMiwiZXhwIjoxNjUyNDQ4MTIyfQ.IxTcu4EFVZ9-p_IEhfI7wVndDUI6UZc5XHgT9PWELMc
